global:
  scrape_interval: 20s # default 1 minute
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - rules/*.rule.yml

scrape_configs:

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [
        'localhost:9090'
      ]

  - job_name: CentOS-0
    scrape_interval: 5s
    static_configs:
      - targets: [
        '192.168.56.100:9100'
      ]

  - job_name: CentOS-1
    scrape_interval: 5s
    static_configs:
      - targets: [
        '192.168.56.101:9100'
      ]

  - job_name: CentOS-2
    scrape_interval: 5s
    static_configs:
      - targets: [
        '192.168.56.102:9100'
      ]

  - job_name: CentOS-3
    scrape_interval: 5s
    static_configs:
      - targets: [
        '192.168.56.103:9100'
      ]

  - job_name: CentOS-4
    scrape_interval: 5s
    static_configs:
      - targets: [
        '192.168.56.104:9100'
      ]

  - job_name: 'blackbox' # blackbox monitoring
    metrics_path: /probe
    scrape_interval: 1m
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://techtalk.vn
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
        
  - job_name: ping_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [
        'ping_exporter:9427'
      ]

  - job_name: 'snmp_exporter'
    static_configs:
      - targets:
        - 192.168.1.2  # SNMP device.
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:port.