version: '3.1'

services:

  snmp:
    image: quay.io/prometheus/snmp-exporter
    volumes:
      - /opt/docker-persist/snmp-exporter:/etc/snmp_exporter
    ports:
      - 9116:9116
      - 116:116/udp
    restart: always
    command: --config.file=/etc/snmp_exporter/snmp.yml


